sonar.organization=andreacanton
sonar.projectKey=andreacanton_andreacanton-website
sonar.sources=.
sonar.tests=test
sonar.exclusions=public/**,drafts/**,dist/**,test/**
sonar.host.url=https://sonarcloud.io